---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}

#!/usr/bin/env Rscript
#Extract Cyanobacteria Index (CI) Values From Individually Processed CI Images
#satellite image resource: https://www.ncei.noaa.gov/access/metadata/landing-page/bin/iso?id=gov.noaa.nodc:NOS-HABOFS-LakeErie
###########################
### Dependencies ####
###########################
#renv::activate()
library(docopt)
library(PBSmapping) 
library(geosphere)
library(data.table)
library(dplyr)
library(stringr)
library(lubridate)
library(raster)
library(ncdf4) #new
library(fields) #new
library(sf)
library(png)
library(readr)
source("code/hab_tracker_2017_code_share/hab_tracker/habtracker_functions.R")

```

```{r}
######################################
#SAMPLE STREAM FOR BULK SAMPLES! 
######################################

input_df <- read_csv(file = "cgrc_CI_individual_tiff_analysis_dayOFcollection.csv")      #Run 24September25, not publishable, initial look (NOAA-GLERL weekly)
#input_df <- read_csv(file = "All3G_CI_individual_tiff_analysis_dayOFcollection.csv")      #Run 4September25, publishable
#input_df <- read_csv(file = "All3G_CI_individual_tiff_analysis_1dayBEFOREcollection.csv") #Run 4September25, publishable
input <- input_df %>%
                      filter(!is.na(location) | !is.na(lat) | !is.na(lon) )
output <- input #make table for adding output results
for (i in seq_len(nrow(input))) {
sample_id <- input$SampleID[i]
sample_name <- input$sample_name[i]
collection_lat <- as.numeric(input$lat[i])   #latitude
collection_lon <- as.numeric(input$lon[i]) #longitude
file_path <- input$location[i]
modis_ci_image_day_before <- input$modis_ci_image_name[i]

tiff_path <- paste0(file_path, modis_ci_image_day_before)
lat <- collection_lat		
lon <- collection_lon

###########################
### Script starts here ####
###########################

#clean up time (if NA, adjust) - 12:00, rad = NA
collection_lat <- as.numeric(lat)   #latitude
collection_lon <- as.numeric(lon)   #longitude

#Next section of script can be divided into two parts:
#
#part 1: 
#Mark Rowe 7-2-2015
#this R script will read a geotiff CI file from Stumpf/Wynne
#and write a CI and chlorophyll *.txt file
#
#part 2:
#take the output from part 1 and compare coordinates from samples of interest
#the output will provide distance between points of ci/chlorophyll readings and sample

########
#Part 1# Process Image to Gather All CI assignments
########

#open the geotiff
r1 <- raster(tiff_path)

# Extract the CRS from 'r1'
crs <- crs(r1)
# Convert the CRS to PROJ string format
prj1 <- wkt(crs)

dfrc_raw <- as.data.frame(r1, xy=TRUE)
names(dfrc_raw) <- c("X","Y","ci")
dfrc_process <- projLatLon(dfrc_raw/1000, prj1)
dfrc_process$ci <- dfrc_process$ci*1000
dfrc_process2 <- dfrc_process[, -c(1:2)] #delete columns 1 through 2 (X and Y)
dfrc <- dfrc_process2 %>%
              mutate(lat = as.numeric(lat),
                     lon = as.numeric(lon),
                     ci = as.numeric(ci))
#ignoring as to calculate whether >50% of measurments are cloud cover or not
#dfrc <- dfrc_process2[dfrc_process2$ci <= 250,] # remove land and cloud pixels

#works, but not using chl for this output, so just ignoring
#dfrc$chl <- 0
#dfrc$chl[dfrc$ci == 0] <- 0
#xx <- which(dfrc$ci %in% 1:250)
#CI <- 10^( dfrc$ci[xx]/100 -4)
#dfrc$chl[xx] <- 12570*CI + 10

########
#Part 2# Isolate CI assignments of interest
########
 
setDT(dfrc)

all_coord <- matrix(c(dfrc$lon, dfrc$lat), ncol = 2)

dfci_results <- distHaversine(all_coord, c(collection_lon,collection_lat))

dfci_results_df <- setNames(data.frame(dfci_results), "dist_m")
dfci_final <- cbind(dfrc, dfci_results_df) %>%
                    mutate(dist_m = as.numeric(dist_m))

nearest <- dfci_final %>% 
              filter(ci <= 250) %>%
              dplyr::arrange(dist_m) %>%
              mutate(nearest_ci = first(ci)) %>%
  summarise(nearest_ci = mean(nearest_ci, na.rm = TRUE)) 

#Onekm_rad <- dfci_final %>%
#              dplyr::arrange(dist_m) %>%
#              mutate(less_than_1km = if_else(dist_m <= 1000, TRUE, FALSE),
#                     count_less_than_1km = sum(less_than_1km == TRUE),
#                     count_less_than_1km_ci_less_equal_250 = sum(less_than_1km & ci <= 250),
#                     count_ratio = count_less_than_1km_ci_less_equal_250/count_less_than_1km,
#                     less50cloudCover = if_else(count_ratio >=.5, TRUE, FALSE)) %>%
#  filter(less_than_1km == TRUE) %>%
#  reframe(avg_1km_rad_ci = mean(ci, na.rm = TRUE),
#            less50cloudCover = less50cloudCover) 

Onekm_rad <- dfci_final %>%
  dplyr::arrange(dist_m) %>%
  mutate(less_than_1km = dist_m <= 1000) %>%
  summarise(
    count_less_than_1km = sum(less_than_1km),
    count_less_than_1km_ci_less_equal_250 = sum(less_than_1km & ci <= 250, na.rm = TRUE),
    count_ratio = count_less_than_1km_ci_less_equal_250 / count_less_than_1km,
    less50cloudCover = count_ratio >= 0.5,
    avg_1km_rad_ci = mean(ci[less_than_1km & ci <= 250], na.rm = TRUE)
  )
  
Fivekm_rad <- dfci_final %>%
  dplyr::arrange(dist_m) %>%
  mutate(less_than_5km = dist_m <= 5000) %>%
  summarise(
    count_less_than_5km = sum(less_than_5km),
    count_less_than_5km_ci_less_equal_250 = sum(less_than_5km & ci <= 250, na.rm = TRUE),
    count_ratio = count_less_than_5km_ci_less_equal_250 / count_less_than_5km,
    less50cloudCover = count_ratio >= 0.5,
    avg_5km_rad_ci = mean(ci[less_than_5km & ci <= 250], na.rm = TRUE)
  )

dfci_final_report <- dfci_final %>% 
              filter(ci <= 250) %>%
              dplyr::arrange(dist_m) %>%
                        mutate(nearest_ci = as.numeric(ci),
                               onekm_rad_ci = as.numeric(Onekm_rad$avg_1km_rad_ci),
                               onekm_less50cloudCover = Onekm_rad$less50cloudCover,
                               fivekm_rad_ci = as.numeric(Fivekm_rad$avg_5km_rad_ci),
                               fivekm_less50cloudCover = Fivekm_rad$less50cloudCover,)

dfci_final_report_summary <- dfci_final_report %>%
                                  slice(1) %>%
                                  dplyr::select(nearest_ci, dist_m, onekm_rad_ci, onekm_less50cloudCover, fivekm_rad_ci, fivekm_less50cloudCover)
                                 
output <- output %>%
            mutate(nearest_ci = if_else(SampleID == sample_id, dfci_final_report_summary$nearest_ci, nearest_ci),
                   dist_m = if_else(SampleID == sample_id, dfci_final_report_summary$dist_m, dist_m),
                   onekm_rad_ci = if_else(SampleID == sample_id, dfci_final_report_summary$onekm_rad_ci, onekm_rad_ci),
                   onekm_less50cloudCover = if_else(SampleID == sample_id, dfci_final_report_summary$onekm_less50cloudCover, onekm_less50cloudCover),
                   fivekm_rad_ci = if_else(SampleID == sample_id, dfci_final_report_summary$fivekm_rad_ci, fivekm_rad_ci),
                   fivekm_less50cloudCover = if_else(SampleID == sample_id, dfci_final_report_summary$fivekm_less50cloudCover, fivekm_less50cloudCover))
}
#write_csv(output, file = "../github/data/notebook3_CIGrab/Output_All3G_CI_individual_tiff_analysis_dayOFcollection_8Sept25.csv") #Run 8September25, publishable
#write_csv(output, file = "../github/data/notebook3_CIGrab/Output_All3G_CI_individual_tiff_analysis_1dayBEFOREcollection_8Sept25.csv") #Run 4September25, publishable
write_csv(output, file = "../github/data/notebook3_CIGrab/Output_cgrc_CI_individual_tiff_analysis_dayOFcollection_24Sept25.csv") 

```
